config/routes.rb
Rails.application.routes.draw do




  resources :departamentos
  resources :usuarios
  resources :mantenis
  


  
root :to => 'menu#inicio'	
  get 'menu/inicio'
  get 'menu/Nosotros'
  post 'pages/mimetodo'
  resources :posts
  get 'proyecto_vista/consultar'
  #welcom / registrar

  get 'welcome/index'
  get 'welcome/RegProy'
  get 'welcome/Cotizaciones'
  get 'welcome/iniciosesion'

  get 'welcome/Servicio'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Routes Yuliza
  get '/proyecto', to: 'proyecto_vista#proyecto'
  get '/proyecto/:id', to: 'proyecto_vista#detalle'
  get '/proyecto_vista/consultar'
  get '/ubicacion',  to: 'proyecto_vista#ubicacion'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
  belongs_to :mantenis
  validates :piso, presence: true
end

app/models/manteni.rb
class Manteni < ApplicationRecord
 		has_many :departamentos, dependent: :destroy
 		
end

app/models/regusu.rb
class Regusu < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento registrado correctamente.' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:piso, :caracteristicas, :area, :tipo, :precio, :mantenis_id)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def inicio
  end
  def Nosotros
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inicio_sesion_helper.rb
module InicioSesionHelper
end

app/helpers/mantenis_helper.rb
module MantenisHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/modelo_helper.rb
module ModeloHelper
end

app/helpers/mproyec_helper.rb
module MproyecHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/proyecto_vista_helper.rb
module ProyectoVistaHelper
end

app/helpers/regusu_helper.rb
module RegusuHelper
end

app/helpers/regusus_helper.rb
module RegususHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento, local: true) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :piso %>
    <%= form.number_field :piso, id: :departamento_piso %>
  </div>

  <div class="field">
    <%= form.label :caracteristicas %>
    <%= form.text_area :caracteristicas, id: :departamento_caracteristicas %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_area :area, id: :departamento_area %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :departamento_tipo %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio, id: :departamento_precio %>
  </div>

  <div class="field">
    <%= form.label :mantenis_id %>
    <%= form.text_field :mantenis_id, id: :departamento_mantenis_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Piso</th>
      <th>Caracteristicas</th>
      <th>Area</th>
      <th>Tipo</th>
      <th>Precio</th>
      <th>Mantenis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.piso %></td>
        <td><%= departamento.caracteristicas %></td>
        <td><%= departamento.area %></td>
        <td><%= departamento.tipo %></td>
        <td><%= departamento.precio %></td>
        <td><%= departamento.mantenis %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Piso:</strong>
  <%= @departamento.piso %>
</p>

<p>
  <strong>Caracteristicas:</strong>
  <%= @departamento.caracteristicas %>
</p>

<p>
  <strong>Area:</strong>
  <%= @departamento.area %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @departamento.tipo %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @departamento.precio %>
</p>

<p>
  <strong>Mantenis:</strong>
  <%= @departamento.mantenis %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>