config/routes.rb
Rails.application.routes.draw do




  resources :departamentos
  resources :usuarios
  resources :mantenis
  


  
root :to => 'menu#inicio'	
  get 'menu/inicio'
  get 'menu/Nosotros'
  post 'pages/mimetodo'
  resources :posts
  get 'proyecto_vista/consultar'
  #welcom / registrar

  get 'welcome/index'
  get 'welcome/RegProy'
  get 'welcome/Cotizaciones'
  get 'welcome/iniciosesion'

  get 'welcome/Servicio'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Routes Yuliza
  get '/proyecto', to: 'proyecto_vista#proyecto'
  get '/proyecto/:id', to: 'proyecto_vista#detalle'
  get '/proyecto_vista/consultar'
  get '/ubicacion',  to: 'proyecto_vista#ubicacion'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
  belongs_to :mantenis
  validates :piso, presence: true
end

app/models/manteni.rb
class Manteni < ApplicationRecord
 		has_many :departamentos, dependent: :destroy
 		
end

app/models/regusu.rb
class Regusu < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/mantenis_controller.rb
class MantenisController < ApplicationController
  before_action :set_manteni, only: [:show, :edit, :update, :destroy]

  # GET /mantenis
  # GET /mantenis.json
  def index
    @mantenis = Manteni.all
  end

  # GET /mantenis/1
  # GET /mantenis/1.json
  def show
  end

  # GET /mantenis/new
  def new
    @manteni = Manteni.new
    @manteni.departamentos.build
  end

  # GET /mantenis/1/edit
  def edit
    @manteni.departamentos.build
  end

  # POST /mantenis
  # POST /mantenis.json
  def create
    @manteni = Manteni.new(manteni_params)

    respond_to do |format|
      if @manteni.save
        format.html { redirect_to @manteni, notice: 'Manteni was successfully created.' }
        format.json { render :show, status: :created, location: @manteni }
      else
        format.html { render :new }
        format.json { render json: @manteni.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mantenis/1
  # PATCH/PUT /mantenis/1.json
  def update
    respond_to do |format|
      if @manteni.update(manteni_params)
        format.html { redirect_to @manteni, notice: 'Manteni was successfully updated.' }
        format.json { render :show, status: :ok, location: @manteni }
      else
        format.html { render :edit }
        format.json { render json: @manteni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mantenis/1
  # DELETE /mantenis/1.json
  def destroy
    @manteni.destroy
    respond_to do |format|
      format.html { redirect_to mantenis_url, notice: 'Manteni was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manteni
      @manteni = Manteni.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manteni_params
      params.require(:manteni).permit(:nombre, :caracteristicas, :areacomun, :pisos, :ubicacion, departamentos_attributes: [:id,
<<<<<<< HEAD
<<<<<<< HEAD
      :piso, :_destroy])
=======
      :piso, :caracteristicas, :area, :tipo, :precio, :_destroy])
>>>>>>> 12d0f8e3b8fc762d4a10aba9ae08c844b116352f
=======
      :piso, :caracteristicas, :area, :tipo, :precio, :_destroy])
>>>>>>> 12d0f8e3b8fc762d4a10aba9ae08c844b116352f
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def inicio
  end
  def Nosotros
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inicio_sesion_helper.rb
module InicioSesionHelper
end

app/helpers/mantenis_helper.rb
module MantenisHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/modelo_helper.rb
module ModeloHelper
end

app/helpers/mproyec_helper.rb
module MproyecHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/proyecto_vista_helper.rb
module ProyectoVistaHelper
end

app/helpers/regusu_helper.rb
module RegusuHelper
end

app/helpers/regusus_helper.rb
module RegususHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/mantenis/_form.html.erb
<%= form_with(model: manteni, local: true) do |form| %>
  <% if manteni.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manteni.errors.count, "error") %> prohibited this manteni from being saved:</h2>

      <ul>
      <% manteni.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div style="margin: 2px 200px 1px 30px">
  
  <div class="field">
    <%= form.label :Nombre %>
    <br>
    <%= form.text_field :nombre, id: :manteni_nombre , :class => 'form-control mb-2 mr-sm-2'%>
  </div>
  <div class="field">
    <%= form.label :Caracteristicas %>
    <br>
    <%= form.text_field :caracteristicas, id: :manteni_caracteristicas, :class => 'form-control mb-2 mr-sm-2' %>
  </div>
 
  <div class="field">
    <%= form.label  :Areas %>
    <br>
    <%= form.text_area :areacomun, id: :manteni_areacomun, :class => 'form-control mb-2 mr-sm-2' %>
  </div>

  <div class="field">
    <%= form.label :Pisos %>
    <br>
    <%= form.number_field :pisos, id: :manteni_pisos, :class => 'form-control mb-2 mr-sm-2' %>
  </div>

  <div class="field">
    <%= form.label :ubicacion %>
    <br>
    <%= form.text_area :ubicacion, id: :manteni_ubicacion , :class => 'form-control mb-2 mr-sm-2'%>
  </div>
<br>
  <h2>Departamentos</h2>
  <%= form.fields_for :departamentos do |departamentos| %>
    <div class="departamentos_fields">
      <div class="fields">
        <%= departamentos.label :piso, "Piso" %>
        <%= departamentos.text_field :piso %>
         <%= departamentos.label :caracteristicas, "Caracteristicas" %>
        <%= departamentos.text_field :caracteristicas %>
         <%= departamentos.label :area, "Area" %>
        <%= departamentos.text_field :area %>
         <%= departamentos.label :tipo, "tipo" %>
        <%= departamentos.text_field :tipo %>
        <%= departamentos.label :precio, "Precio" %>
        <%= departamentos.text_field :precio %>


        <%= departamentos.check_box :_destroy %>
        <%= departamentos.label :_destroy, "Borrar" %>
      </div>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
 
  </div>
<% end %>

app/views/mantenis/edit.html.erb
<h1 style="text-align: center; letter-spacing: 3px">Editar Proyecto</h1>

<%= render 'form', manteni: @manteni %>

<%= link_to 'Mostrar', @manteni %> |
<%= link_to 'Atras', mantenis_path %>

app/views/mantenis/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center;">Mantenimiento de proyecto</h1><br>
<table class="table">
  <thead class="thead-dark" style="text-align: center;">
    <tr>
      <th>Nombre</th>
      <th>Caracteristicas</th>
      <th>Areas Comunes</th>
      <th>Pisos</th>
      <th>Ubicacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mantenis.each do |manteni| %>
      <tr>
        <td><%= manteni.nombre %></td>
        <td><%= manteni.caracteristicas %></td>
        <td><%= manteni.areacomun %></td>
        <td><%= manteni.pisos %></td>
        <td><%= manteni.ubicacion %></td>
        <!--<td><%= link_to 'Registrar', manteni %></td>-->
        <td><%= link_to 'Editar', edit_manteni_path(manteni) %></td>
        <td><%= link_to 'Eliminar', manteni, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div type="button" class="btn btn-outline-dark">
<%= link_to 'Nuevo proyecto', new_manteni_path %>
</div>

app/views/mantenis/new.html.erb
<h1>Registrar Proyecto</h1>

<%= render 'form', manteni: @manteni %>
<br>
<div type="button" class="btn btn-outline-dark">
<%= link_to 'Atras', mantenis_path %>
</div>

app/views/mantenis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @manteni.nombre %>
</p>

<p>
  <strong>Caracteristicas:</strong>
  <%= @manteni.caracteristicas %>
</p>

<p>
  <strong>Areas Comunes:</strong>
  <%= @manteni.areacomun %>
</p>

<p>
  <strong>Pisos:</strong>
  <%= @manteni.pisos %>
</p>

<p>
  <strong>Ubicacion:</strong>
  <%= @manteni.ubicacion %>
</p>




<h2>Sucursales</h2>
<% if @manteni.departamento.any? %>
  <ul>
    <% @manteni.departamento.each do |departamentos| %>
    <li><%= link_to departamentos, departamentos %></li>
    <% end %>
  </ul>
<% else %>
  <p> No hay Sucursales </p>
  <% end %>
<%= link_to 'Editar', edit_manteni_path(@manteni) %> |
<%= link_to 'Atras', mantenis_path %>