config/routes.rb
Rails.application.routes.draw do




  resources :departamentos
  resources :usuarios
  resources :mantenis
  


  
root :to => 'menu#inicio'	
  get 'menu/inicio'
  get 'menu/Nosotros'
  post 'pages/mimetodo'
  resources :posts
  get 'proyecto_vista/consultar'
  #welcom / registrar

  get 'welcome/index'
  get 'welcome/RegProy'
  get 'welcome/Cotizaciones'
  get 'welcome/iniciosesion'

  get 'welcome/Servicio'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Routes Yuliza
  get '/proyecto', to: 'proyecto_vista#proyecto'
  get '/proyecto/:id', to: 'proyecto_vista#detalle'
  get '/proyecto_vista/consultar'
  get '/ubicacion',  to: 'proyecto_vista#ubicacion'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
  belongs_to :mantenis
  validates :piso, presence: true
end

app/models/manteni.rb
class Manteni < ApplicationRecord
 		has_many :departamentos, dependent: :destroy
 		
end

app/models/regusu.rb
class Regusu < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def inicio
  end
  def Nosotros
  	
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :email, :cont, :dni, :fech, :telef, :direccion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inicio_sesion_helper.rb
module InicioSesionHelper
end

app/helpers/mantenis_helper.rb
module MantenisHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/modelo_helper.rb
module ModeloHelper
end

app/helpers/mproyec_helper.rb
module MproyecHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/proyecto_vista_helper.rb
module ProyectoVistaHelper
end

app/helpers/regusu_helper.rb
module RegusuHelper
end

app/helpers/regusus_helper.rb
module RegususHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div style="margin: 2px 200px 1px 30px">
  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :usuario_nombre  , :class => 'form-control '%>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido, id: :usuario_apellido , :class => 'form-control '%>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_area :email, id: :usuario_email, :class => 'form-control ' %>
  </div>

  <div class="field">
    <%= form.label :contraseña %>
    <%= form.text_area :cont, id: :usuario_cont, :class => 'form-control ' %>
  </div>

  <div class="field">
    <%= form.label "Documento de identidad"%>
    <%= form.number_field :dni, id: :usuario_dni, :class => 'form-control ' %>
  </div>
<br>
  <div class="field">
    <%= form.label "Fecha de nacimiento" %>
    <%= form.date_select :fech, id: :usuario_fech , :class => 'form-control mb-2 mr-sm-2 '%>
  </div>

  <div class="field">
    <%= form.label :Telefono %>
    <%= form.number_field :telef, id: :usuario_telef, :class => 'form-control ' %>
  </div>

  <div class="field">
    <%= form.label :Direccion %>
    <%= form.text_area :direccion, id: :usuario_direccion, :class => 'form-control ' %>
  </div>

<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/usuarios/edit.html.erb
<h1 style="text-align: center; letter-spacing: 3px">Editar usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Mostrar', @usuario %> |
<%= link_to 'Atras', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center; letter-spacing: 3px">Usuarios</h1>

<table class="table">
  <thead>
    <tr  class="table-primary">
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th>Contraseña</th>
      <th>Dni</th>
      <th>Fecha de Nacimiento</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.cont %></td>
        <td><%= usuario.dni %></td>
        <td><%= usuario.fech %></td>
        <td><%= usuario.telef %></td>
        <td><%= usuario.direccion %></td>
        <!--<td><%= link_to 'Show', usuario %></td>-->
        <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Eliminar', usuario, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar nuevo usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1 style="text-align: center; letter-spacing: 3px">Nuevo usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
  <thead>
    <tr  class="table-danger">
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th>Contraseña</th>
      <th>Dni</th>
      <th>Fecha de Nacimiento</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody class="table-success">
  <th>

  <%= @usuario.nombre %>

</th>
<th>
    <%= @usuario.apellido %>
</th>
<th>

  <%= @usuario.email %>

</th>
<th>

  <%= @usuario.cont %>

</th>
<th>


  <%= @usuario.dni %>

</th>
<th>

  <%= @usuario.fech %>

</th>
<th>

  <%= @usuario.telef %>

</th>
<th>

  <%= @usuario.direccion %>

</th>
</tbody>
</table>
<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Atras', usuarios_path %>